# Generated by Django 6.0.5 on 2026-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapitaal', models.FloatField()),
                ('rente', models.FloatField()),
                ('looptijd', models.FloatField()),
                ('eindbedrag', models.FloatField()),
                ('rentewinst', models.FloatField()),
                ('datum_berekening', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
